# Generated by Django 4.1.7 on 2023-03-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_date_created_post_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default.jpeg', upload_to='static/thumbnails/'),
        ),
    ]
